/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 27-ноя-2023 12:53:36 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Marks_Students]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Marks] DROP CONSTRAINT [FK_Marks_Students]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Marks_Subjects]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Marks] DROP CONSTRAINT [FK_Marks_Subjects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Students_SchoolClasses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Students] DROP CONSTRAINT [FK_Students_SchoolClasses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_StudentsGuardians_Guardians]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [StudentsGuardians] DROP CONSTRAINT [FK_StudentsGuardians_Guardians]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_StudentsGuardians_Students]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [StudentsGuardians] DROP CONSTRAINT [FK_StudentsGuardians_Students]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Teachers_SchoolClasses]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Teachers] DROP CONSTRAINT [FK_Teachers_SchoolClasses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Teachers_Subjects]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Teachers] DROP CONSTRAINT [FK_Teachers_Subjects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_Users_Roles]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [Users] DROP CONSTRAINT [FK_Users_Roles]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Guardians]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Guardians]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Marks]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Marks]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Roles]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Roles]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[SchoolClasses]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [SchoolClasses]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Students]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Students]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[StudentsGuardians]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [StudentsGuardians]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Subjects]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Subjects]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Teachers]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Teachers]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[Users]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [Users]
GO

/* Create Tables */

CREATE TABLE [Guardians]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[firstName] nvarchar(50) NOT NULL,
	[middleName] nvarchar(50) NOT NULL,
	[lastName] nvarchar(50) NOT NULL,
	[address] nvarchar(100) NOT NULL,
	[cellPhone] varchar(13) NULL
)
GO

CREATE TABLE [Marks]
(
	[dateOfIssue] date NOT NULL,
	[subjectId] int NOT NULL,
	[studentId] int NOT NULL,
	[name] int NOT NULL
)
GO

CREATE TABLE [Roles]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[name] nvarchar(50) UNIQUE NOT NULL
)
GO

CREATE TABLE [SchoolClasses]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[name] nvarchar(3) UNIQUE NOT NULL
)
GO

CREATE TABLE [Students]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[firstName] nvarchar(30) NOT NULL,
	[middleName] nvarchar(30) NOT NULL,
	[lastName] nvarchar(30) NOT NULL,
	[address] nvarchar(100) NOT NULL,
	[dob] date NOT NULL,
	[cellPhone] varchar(13) NULL,
	[classId] int NOT NULL
)
GO

CREATE TABLE [StudentsGuardians]
(
	[studentId] int NOT NULL,
	[guardianId] int NOT NULL
)
GO

CREATE TABLE [Subjects]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[name] nvarchar(50) UNIQUE NOT NULL
)
GO

CREATE TABLE [Teachers]
(
	[id] int NOT NULL IDENTITY (1, 1),
	[firstName] nvarchar(50) NOT NULL,
	[middleName] nvarchar(50) NOT NULL,
	[lastName] nvarchar(50) NOT NULL,
	[address] nvarchar(100) NOT NULL,
	[dob] date NOT NULL,
	[cellPhone] varchar(13) NULL,
	[classId] int NULL,
	[subjectId] int NOT NULL
)
GO

CREATE TABLE [Users]
(
	[login] varchar(50) NOT NULL,
	[password] varchar(50) NOT NULL,
	[roleId] int NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Guardians] 
 ADD CONSTRAINT [PK_Guardians]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Marks] 
 ADD CONSTRAINT [PK_Marks]
	PRIMARY KEY CLUSTERED ([dateOfIssue] ASC,[subjectId] ASC,[studentId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Marks_Students] 
 ON [Marks] ([studentId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Marks_Subjects] 
 ON [Marks] ([subjectId] ASC)
GO

ALTER TABLE [Roles] 
 ADD CONSTRAINT [PK_Roles]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [SchoolClasses] 
 ADD CONSTRAINT [PK_SchoolClasses]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Students] 
 ADD CONSTRAINT [PK_Students]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Students_SchoolClasses] 
 ON [Students] ([classId] ASC)
GO

ALTER TABLE [StudentsGuardians] 
 ADD CONSTRAINT [PK_StudentsGuardians]
	PRIMARY KEY CLUSTERED ([studentId] ASC,[guardianId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_StudentsGuardians_Guardians] 
 ON [StudentsGuardians] ([guardianId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_StudentsGuardians_Students] 
 ON [StudentsGuardians] ([studentId] ASC)
GO

ALTER TABLE [Subjects] 
 ADD CONSTRAINT [PK_Subjects]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

ALTER TABLE [Teachers] 
 ADD CONSTRAINT [PK_Teachers]
	PRIMARY KEY CLUSTERED ([id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Teachers_SchoolClasses] 
 ON [Teachers] ([classId] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Teachers_Subjects] 
 ON [Teachers] ([subjectId] ASC)
GO

ALTER TABLE [Users] 
 ADD CONSTRAINT [PK_Users]
	PRIMARY KEY CLUSTERED ([login] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_Users_Roles] 
 ON [Users] ([roleId] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [Marks] ADD CONSTRAINT [FK_Marks_Students]
	FOREIGN KEY ([studentId]) REFERENCES [Students] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Marks] ADD CONSTRAINT [FK_Marks_Subjects]
	FOREIGN KEY ([subjectId]) REFERENCES [Subjects] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Students] ADD CONSTRAINT [FK_Students_SchoolClasses]
	FOREIGN KEY ([classId]) REFERENCES [SchoolClasses] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [StudentsGuardians] ADD CONSTRAINT [FK_StudentsGuardians_Guardians]
	FOREIGN KEY ([guardianId]) REFERENCES [Guardians] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [StudentsGuardians] ADD CONSTRAINT [FK_StudentsGuardians_Students]
	FOREIGN KEY ([studentId]) REFERENCES [Students] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Teachers] ADD CONSTRAINT [FK_Teachers_SchoolClasses]
	FOREIGN KEY ([classId]) REFERENCES [SchoolClasses] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Teachers] ADD CONSTRAINT [FK_Teachers_Subjects]
	FOREIGN KEY ([subjectId]) REFERENCES [Subjects] ([id]) ON DELETE No Action ON UPDATE No Action
GO

ALTER TABLE [Users] ADD CONSTRAINT [FK_Users_Roles]
	FOREIGN KEY ([roleId]) REFERENCES [Roles] ([id]) ON DELETE No Action ON UPDATE No Action
GO
